### PR TITLE
Convert components to classes.

### PR DESCRIPTION
**Pull request by svenvandescheur**
This makes the library work with more recent React versions.

### CODE REVIEW

**Comment by svenvandescheur** [comment]
Hi @hawkrives 

There is a little bit of JSX here: https://github.com/hawkrives/react-list-select/blob/master/List.es6#L193

This causes my build to fail, adding `babel-preset-react` resolved that for me.

**Comment by hawkrives** [comment]
Ah, so there is JSX. Good catch.

If you revert your version number bump commit, I'll gladly merge and release this 😄

**Comment by svenvandescheur** [comment]
Awesome :)

I've reverted the version bump.

**Comment by hawkrives** [comment]
Well, that cascaded a bit. If v0.4.0 doesn't work for you, please let me know.

I've added a changelog to the repo, so I'll direct you there.

**Comment by hawkrives** [comment]
(@svenvandescheur)

**Comment by svenvandescheur** [comment]
@hawkrives Thanks, Yes 0.4.0 works perfectly, thanks for helping out.

**Pull request merged**
